#!/usr/bin/env bash

readonly BASEDIR=$(dirname $(dirname ${BASH_SOURCE[0]}))
. $BASEDIR/lifecycle/common.sh

ulimit -u unlimited

COMMAND="node $BASEDIR/lifecycle/bin/deploy.js $*"
sudo "PATH=$PATH" -u admin -i $COMMAND 2>&1 | pipe_log_info >> $DEPLOY_LOGFILE || deploy_error_exit "Deploy fail"
